name: Run mocha tests
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: 'Node.js v16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with: 
          node-version: '16'
      - uses: actions/checkout@v2
      - name: 'Cache node_modules'
        uses: actions/cache@v2
        with: ~./.npm
        key: ${{ runner.os }}-node-v16-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-v16-
      - name: Install Dependencies
        run: npm install
      - name: Run mocha tests
        run: npm run test

